#
# compose.env.staging.yml - Staging environment
# Usage: docker compose -f compose.yaml -f compose.env.staging.yml up -d
#

services:

    db:
        environment:
            - POSTGRES_HOST=postgresql-container
            - POSTGRES_MAX_CONNECTIONS=100
        profiles:
            - staging

    php:
        environment:
            - APP_ENV=staging
            - PHP_DISPLAY_ERRORS=0
        profiles:
            - staging

    webserver:
        labels:
            - "env=staging"
        profiles:
            - staging