#
# docker-compose.yml - yml script to execute docker commands to generate images 
#                      and containers to the project.
#
# created: 2022-12-07
# author: albert r. carnier guedes (albert@teko.net.br)
# 
# Distributed under the MIT License. See LICENSE for more information.
#
version: '3.8'

services:

    # Create the database image and container.
    db:

        # Create the image.        
        build: 
            context: ./db/
            dockerfile: postgresql.dockerfile
        
        # Custom name for the image.
        image: postgresql-image

        # Custom name for the container.
        container_name: postgresql-container

        # Expose the port "5432" on host port "2345".
        ports: 
            - "2345:5432"

    # Create the php-fpm server image and container.
    php:

        # Create the image.        
        build: 
            context: ./php/
            dockerfile: php.dockerfile
        
        # Custom name for the image.
        image: php-fpm-image

        # Custom name for the container.
        container_name: php-fpm-container

        # Expose the port "9000" on host port "9090".
        ports: 
            - "9090:9000"

        volumes:
            - ./app:/var/www/html

    # Create the webserver image and container.
    webserver:

        # Create the image.        
        build: 
            context: ./webserver/
            dockerfile: nginx.dockerfile
        
        # Custom name for the image.
        image: nginx-image

        # Custom name for the container.
        container_name: nginx-container

        # Expose the port "80" on host port "8080".
        ports: 
            - "8080:80"
