#
# filter.d/nginx-auth.conf - Fail2ban filter for nginx authentication failures
#
[Definition]
failregex = no user/password was authenticated for client IP <HOST>
            user .* was not found in ".+" at client IP <HOST>
            user password mismatch for client IP <HOST>
ignoreregex =