#
# filter.d/nginx-noscript.conf - Fail2ban filter for missing scripts
#
[Definition]
failregex = ^<HOST> -.*GET.*(ajax|image|apps|api|icons|robots\.txt|favicon\.ico).*$
            ^<HOST> -.*GET.*/\.git/.*
ignoreregex =